apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-internal-whoami
  namespace: argocd
spec:
  project: internal-apps
  source:
    repoURL: https://gitea.home.arpa/felstormrage/kairos.git
    targetRevision: main
    path: apps/internal/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
