apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-external-whoami
  namespace: argocd
spec:
  project: external-apps
  source:
    repoURL: https://gitea.home.arpa/felstormrage/kairos.git
    targetRevision: main
    path: apps/external/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
