apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-namespaces
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://gitea.home.arpa/felstormrage/kairos.git
    targetRevision: main
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
